server:
  port: 8100

spring:
  datasource:
    driverClassName: "com.mysql.jdbc.Driver"
    url: "jdbc:mysql://127.0.0.1:3306/db_bc2408_yahoofinance"
    username: root
    password: 
  jpa:
    show-sql: true
    hibernate.ddl-auto: update