server:
  port: 8081

api:
  jph:
    domain: "jsonplaceholder.typicode.com"
    endpoints:
      users: "/users"

spring:
  datasource:
    driverClassName: "com.mysql.jdbc.Driver"
    url: "jdbc:mysql://127.0.0.1:3306/db_bc2408"
    username: root
    password: 
  jpa:
    show-sql: true
    hibernate.ddl-auto: create